version: "3.9"

services:
  loadbalancer:
    image: nginx:alpine
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "4000:4000"
    depends_on:
      - auth-service

  auth-service:
    build: ./auth-service
    environment:
      PORT: 4001
      DATABASE_HOST: auth-db
      DATABASE_PASSWORD: pwd
      DATABASE_USER: postgres
      DATABASE: authdb
      DATABASE_PORT: 5432
      REDIS_URL: redis://authcache
    volumes:
      - ./auth-service/src:/app/src
    expose:
      - 4001

    depends_on:
      - auth-db
      - auth-cache

  auth-db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: pwd
      POSTGRES_USER: postgres
      POSTGRES_DB: authdb
    volumes:
      - authdb:/var/lib/postgresql/data
    expose:
      - 5432

  auth-cache:
    image: redis:alpine
    container_name: authcache
    expose:
      - 6379

  file-service:
    build: ./file-service
    volumes:
      - ./file-service/src:/app/src
      - filestore:/app/filestore

    ports:
      - "4002:4002"

  web-client:
    build: ./web-client
    volumes:
      - ./web-client/src:/app/src

volumes:
  authdb:
  filestore:
