# Cache for auth
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-cache
  labels:
    app: auth-cache
spec:
  selector:
    matchLabels:
      app: auth-cache-pod
  template:
    metadata:
      name: auth-cache-pod
      labels:
        app: auth-cache-pod
    spec:
      containers:
        - name: auth-cache-container
          image: redis:alpine
---
# Service for auth cache
apiVersion: v1
kind: Service
metadata:
  name: auth-cache-service
  labels:
    app: auth-cache-service
spec:
  ports:
    - port: 80
      targetPort: 6379
      name: auth-cache-port
  selector:
    app: auth-cache-pod
---
# Service for db statefull set
apiVersion: v1
kind: Service
metadata:
  name: auth-db-service
  labels:
    app: auth-db-service
spec:
  ports:
    - port: 80
      targetPort: 5432
      name: auth-db-port
  selector:
    app: auth-db-pod
---
# Pvc claim for db
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-db-vol-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# Database for auth
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auth-db
spec:
  selector:
    matchLabels:
      app: auth-db-pod
  replicas: 1
  serviceName: "auth-db-service"
  template:
    metadata:
      labels:
        app: auth-db-pod
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: auth-db-container
          image: postgres:alpine
          env:
            - name: POSTGRES_PASSWORD
              value: "pwd"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_DB
              value: "authdb"
          ports:
            - containerPort: 5432
              name: db-port
          volumeMounts:
            - name: auth-vol
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: auth-vol
          persistentVolumeClaim:
            claimName: auth-db-vol-claim
---
# Deployment for the auth
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
  labels:
    app: auth-deployment
spec:
  selector:
    matchLabels:
      app: auth-pod
  template:
    metadata:
      name: auth-pod
      labels:
        app: auth-pod
    spec:
      containers:
        - name: auth-container
          image: beepchat/beep-auth-service:dep-less
          ports:
            - containerPort: 80
              name: auth-cont-port
          env:
            - name: PORT
              value: "80"
            - name: DATABASE_HOST
              value: auth-db-service
            - name: DATABASE_PASSWORD
              value: pwd
            - name: DATABASE_USER
              value: postgres
            - name: DATABASE
              value: authdb
            - name: DATABASE_PORT
              value: "80"
            - name: REDIS_URL
              value: "redis://auth-cache-service"
---
# auth-service
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: auth-pod
